name: Bugus Created

on:
  issues:
    types:
      - labeled
      
jobs:
  bogus:
    if: github.event.label.name == 'bogus'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Analyze
        id: analyze
        uses: zentered/issue-forms-body-parser@v1.4.3
      - run: |
          cat << EOF
          '${{ toJSON(github.event) }}'
          EOF
      - run: |
          cat << EOF
          '${{ steps.analyze.outputs.data }}'
          EOF
      
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            You mentioned an issue in version ${{ steps.analyze.outputs.data.version.text }}. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:

      
      - name: close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            We are done. :sparkles: Thank you for your contribution! :sparkles:
