name: Bugus Created

on:
  issues:
    types:
      - opened
      - edited
#      - labeled
      
jobs:
  bogus:
#    if: github.event.label.name == 'bogus'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Analyze
        id: analyze
        uses: zentered/issue-forms-body-parser@v1.4.3
      - run: echo ${{ toJSON(github.event) }}
      - run: echo ${{ toJSON(steps.analyze.outputs.data) }}
      
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v2.0.0
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles:
